version: '3.9'

services:
  db:
    image:  ankane/pgvector:latest
    shm_size: 128mb
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:  
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres-data: