services:
  db:
    image: ankane/pgvector:latest
    networks:
      - eliza-network 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Eliza
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - eliza-network
volumes:
  postgres_data:

networks:
  eliza-network:
    driver: bridge